version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: mateus
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: aulas
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
